### ISSUE TITLE
Glossary Mojo : Failure on Windows

### ISSUE THREAD

**Issue by javathought** [binout/livingdoc-maven-plugin#14]
The mojo fails on Windows, trying to access the asciidoc generated file. the plugin is called with default format value : html

The adoc is well generated : all annoted classes have they description in the generated file.

` java.nio.file.FileSystemException: C:\dva\projets\tc\model\target\generated-docs\glossary.adoc: Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processus`

The configuration used : 

```
[DEBUG] Configuring mojo 'io.github.livingdocumentation:livingdoc-maven-plugin:0.1:glossary' with basic configurator -->
[DEBUG]   (f) annotation = Glossary
[DEBUG]   (f) format = html
[DEBUG]   (f) outputDirectory = C:\dva\projets\tc\model\target\generated-docs
[DEBUG]   (f) sources = [C:\dva\projets\tc\model\src\main\java]
[DEBUG] -- end configuration --
```

```
[ERROR] Failed to execute goal io.github.livingdocumentation:livingdoc-maven-plugin:0.1:glossary (default-cli) on project tc-model: Execution default-cli of goal io.github.livingdocumentation:livingdoc-maven-plugin:0.1:glossary failed: java.nio.file.FileSystemException: C:\dva\projets\tc\model\target\generated-docs\glossary.adoc: Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processus. -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal io.github.livingdocumentation:livingdoc-maven-plugin:0.1:glossary (default-cli) on project tc-model: Execution default-cli of goal io.github.livingdocumentation:livingdoc-maven-plugin:0.1:glossary failed: java.nio.file.FileSystemException: C:\dva\projets\tc\model\target\generated-docs\glossary.adoc: Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processus.

	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:225)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:153)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:145)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:84)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:59)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.singleThreadedBuild(LifecycleStarter.java:183)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:161)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:320)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:156)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:537)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:196)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:141)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:290)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:230)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
	at org.codehaus.classworlds.Launcher.main(Launcher.java:47)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution default-cli of goal io.github.livingdocumentation:livingdoc-maven-plugin:0.1:glossary failed: java.nio.file.FileSystemException: C:\dva\projets\tc\model\target\generated-docs\glossary.adoc: Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processus.

	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:110)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:209)
	... 25 more
Caused by: java.io.UncheckedIOException: java.nio.file.FileSystemException: C:\dva\projets\tc\model\target\generated-docs\glossary.adoc: Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processus.

	at maven.GlossaryMojo.execute(GlossaryMojo.java:65)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:101)
	... 26 more
Caused by: java.nio.file.FileSystemException: C:\dva\projets\tc\model\target\generated-docs\glossary.adoc: Le processus ne peut pas accéder au fichier car ce fichier est utilisé par un autre processus.

	at sun.nio.fs.WindowsException.translateToIOException(WindowsException.java:86)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:97)
	at sun.nio.fs.WindowsException.rethrowAsIOException(WindowsException.java:102)
	at sun.nio.fs.WindowsFileSystemProvider.implDelete(WindowsFileSystemProvider.java:269)
	at sun.nio.fs.AbstractFileSystemProvider.deleteIfExists(AbstractFileSystemProvider.java:108)
	at java.nio.file.Files.deleteIfExists(Files.java:1165)
	at maven.GlossaryMojo.execute(GlossaryMojo.java:62)
	... 27 more
[ERROR] 
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException

Process finished with exit code 1

```

**Comment by javathought** [comment]
Milestone removed. Workaround implemented to avoid failure of goal
Linked to asciidoctor/asciidoctor#1897 (as mentioned in asciidoctor/asciidoctorj#524).

It's fixed on milestone v1.5.6, no due date

**Comment by javathought** [comment]
workaround tested and validated

**Comment by binout** [comment]
Closed with https://github.com/LivingDocumentation/livingdoc-maven-plugin/pull/23
